# 数据操作

In [2]:
import torch

## 入门

In [11]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
x.shape

torch.Size([12])

In [15]:
x.size()

torch.Size([12])

In [12]:
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
zero_x = torch.zeros(2, 3, 4)
zero_x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
one_x = torch.ones(6, 4)
one_x

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [15]:
empty_x = torch.empty(5, 3)
empty_x

tensor([[1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39],
        [9.9184e-39, 8.4490e-39, 9.6429e-39],
        [1.0653e-38, 1.0469e-38, 4.2246e-39]])

In [16]:
rand_x = torch.rand(5, 3)
rand_x

tensor([[0.5434, 0.9915, 0.1722],
        [0.1632, 0.7183, 0.8287],
        [0.7440, 0.2739, 0.8079],
        [0.8939, 0.1152, 0.0420],
        [0.8216, 0.4202, 0.2045]])

In [21]:
normal_x = torch.randn(3, 3)
print(normal_x)

tensor([[-1.9073, -0.9290,  0.4442],
        [-1.0069,  1.0009,  0.4646],
        [ 0.5002, -1.9669, -0.9983]])


In [17]:
tensor1 = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
tensor1

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [18]:
tensor2 = torch.randn_like(tensor1, dtype=torch.float)
tensor2, tensor2.size()

(tensor([[ 0.6537, -1.3841, -1.1615, -1.4433],
         [ 0.5869,  0.0705,  0.5549,  1.0482],
         [-0.3752, -0.3080,  0.9360, -0.4341]]),
 torch.Size([3, 4]))

## 运算符

In [2]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x+y, x-y, x*y, x/y, x**y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [3]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [21]:
X = torch.arange(12).reshape((3,4))
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [ 2,  1,  4,  3],
         [ 1,  2,  3,  4],
         [ 4,  3,  2,  1]]),
 tensor([[ 0,  1,  2,  3,  2,  1,  4,  3],
         [ 4,  5,  6,  7,  1,  2,  3,  4],
         [ 8,  9, 10, 11,  4,  3,  2,  1]]))

In [22]:
X == Y, X < Y, X > Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [23]:
X.sum()

tensor(66)

## 广播机制

In [6]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [7]:
a + b  # a复制列，b复制行

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

In [8]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
X[-1], X[1:3]

(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

In [10]:
X[1, 2] = 9
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

In [19]:
X[0:2, :] = 666
X

tensor([[666, 666, 666, 666],
        [666, 666, 666, 666],
        [  8,   9,  10,  11]])

## 转换为其他Python对象

In [27]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [28]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

# 数据预处理

## 读取数据集

In [24]:
import os

# 在当前目录创建文件夹
os.makedirs(os.path.join('.', 'data'), exist_ok=True)

# 创建文件
data_file = os.path.join('.', 'data', 'house_tiny.csv')

# 打开文件并写入数据
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [25]:
import pandas as pd
data = pd.read_csv('data/house_tiny.csv')
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## 处理缺失值

In [41]:
# 将数据分为输入与输出
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, -1]

# 用均值填充缺失值
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())

print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [42]:
# One-hot编码
inputs = pd.get_dummies(inputs, dummy_na=True)

# 将布尔值转换为整数
inputs = inputs.astype(int)

print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0         3           1          0
1         2           0          1
2         4           0          1
3         3           0          1


## 转换为张量格式

In [34]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

# 线性代数

## 标量

In [35]:
x = torch.tensor(3.0)
y = torch.tensor(2.0)
x+y, x-y, x*y, x/y, x**y

(tensor(5.), tensor(1.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量

In [36]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [37]:
x[3]

tensor(3)

In [38]:
len(x)

4

In [39]:
x.shape

torch.Size([4])

## 矩阵

In [40]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [43]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [45]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [47]:
B == B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

## 张量

In [48]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [64]:
A = torch.arange(20, dtype=float).reshape(5, 4)
B = A.clone()
A, A+B, A*B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]], dtype=torch.float64),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]], dtype=torch.float64),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]], dtype=torch.float64))

In [56]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a+X, a*X, (a*X).shape, 

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

## 降维

In [57]:
x = torch.arange(4)
x, x.sum()

(tensor([0, 1, 2, 3]), tensor(6))

In [58]:
A = torch.arange(20).reshape(5, 4)
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190))

In [59]:
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [61]:
A.sum(axis=0), A.sum(axis=1)

(tensor([40, 45, 50, 55]), tensor([ 6, 22, 38, 54, 70]))

In [65]:
A.mean(), A.mean(axis=0), A.mean(axis=1)

(tensor(9.5000, dtype=torch.float64),
 tensor([ 8.,  9., 10., 11.], dtype=torch.float64),
 tensor([ 1.5000,  5.5000,  9.5000, 13.5000, 17.5000], dtype=torch.float64))

In [66]:
sum_A = A.sum(axis=1, keepdims=True)
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]], dtype=torch.float64)

In [67]:
A / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]], dtype=torch.float64)

In [68]:
A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]], dtype=torch.float64)

## 点积与矩阵乘法

In [70]:
x = torch.arange(4, dtype=float)
y = torch.ones(4, dtype=float)
x, y, x@y

(tensor([0., 1., 2., 3.], dtype=torch.float64),
 tensor([1., 1., 1., 1.], dtype=torch.float64),
 tensor(6., dtype=torch.float64))

In [73]:
A = torch.arange(20, dtype=float).reshape(5, 4)
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.], dtype=torch.float64))

In [77]:
B = torch.ones(4, 3, dtype=float)
torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]], dtype=torch.float64)

## 范数

In [78]:
u = torch.tensor([3.0, -4.0])
# L2范数
torch.norm(u)

tensor(5.)

In [79]:
# L1范数
torch.abs(u).sum()

tensor(7.)

In [80]:
# Frobenius范数
torch.norm(torch.ones(4, 9))

tensor(6.)

# 自动微分

## 简单例子

In [93]:
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [94]:
x.requires_grad_(True)  # 等价于x=torch.arange(4.0,requires_grad=True)
print(x.grad)  # 默认值是None

None


In [95]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

In [96]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [91]:
x.grad == 4*x

tensor([True, True, True, True])

In [97]:
# 默认情况下，PyTorch会累积梯度，因此需要清除之前的值
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [2]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [4]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [10]:
z = 3*y*y
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


## 非标量变量的反向传播

In [99]:
# 对非标量调用backward需要传入一个gradient参数，该参数指定微分函数关于self的梯度。
x.grad.zero_()
y = x * x
y.backward(torch.ones(len(x)))  # 等价于y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

## 分离计算

In [100]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x

z.sum().backward()
x.grad

tensor([0., 1., 4., 9.])

In [101]:
x.grad == u

tensor([True, True, True, True])

In [103]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [104]:
x.grad == 2*x

tensor([True, True, True, True])

## Python控制流的梯度计算

In [105]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [107]:
# 创建没有形状的张量，即标量
a = torch.randn(size=(), requires_grad=True)  
d = f(a)
d.backward()

In [109]:
a.grad == d/a

tensor(True)